server:
    port: 8080
#数据库配置信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dnsxo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  #模板引擎配置
  thymeleaf:
    encoding: UTF-8