spring:
  profiles:
    active: dev

#静态资源配置
  resources:
    static-locations: classpath:/bootstrap
  mvc:
    static-path-pattern: /resources/**
#    active: test
#    active: prod

mybatis:
  mapperLocations: classpath:mapping/*Mapping.xml
  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.dnsxo.bean
